import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import get from '../js/get'
import post from '../js/post'

export default function Home() {

  const [op1, setOp1] = useState(0);
  const [op2, setOp2] = useState(0);
  const [result, setResult] = useState(null);

  let calculate = async () => {
    let results = await post(`/api/add`, {op1, op2});
    setResult(results.result);
    setOp1(0)
    setOp2(0)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Devops Addition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Addition App
        </h1>

        <p className={styles.description}>
          Best software to add two numbers together!
        </p>
        {result != null &&
          <p className={styles.description} style={{color: "green", fontWeight: "bold"}}>
            Total: {result}
          </p>
        }
        <div className={styles.formItems}>
          <div>1. Operant: <input type="number" min={0} max={1000} value={op1} onChange={(e) => setOp1(e.target.value)}/></div>
          <div>2. Operant: <input type="number" min={0} max={1000} value={op2} onChange={(e) => setOp2(e.target.value)}/></div>

          <div><button onClick={() => calculate()}>Calculate</button></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
